stages:
  - test

test-ruby32:
  stage: test
  image: ruby:3.2.0
  script:
    - bundle install
    - SERIALIZER=marshal bundle exec rake
    - SERIALIZER=json bundle exec rake
    - SERIALIZER=yaml bundle exec rake
    - SERIALIZER=pure bundle exec rake
