stages:
  - test

test-ruby32:
  stage: test
  image: ruby:3.2.0
  script:
    - bundle install
    - SERIALIZER=marshal ./bin/run-tests
    - SERIALIZER=json ./bin/run-tests
    - SERIALIZER=yaml ./bin/run-tests
    - SERIALIZER=plain ./bin/run-tests
