stages:
  - test

test-ruby32:
  stage: test
  image: ruby:3.2.0
  script:
    - bundle install
    - SERIALIZER=marshal for t in *_test.rb; do ruby test/${t}; done
    - SERIALIZER=json for t in *_test.rb; do ruby test/${t}; done
    - SERIALIZER=yaml for t in *_test.rb; do ruby test/${t}; done
    - SERIALIZER=pure for t in *_test.rb; do ruby test/${t}; done
