stages:
  - test

test-ruby31:
  stage: test
  image: ruby:3.1.2
  script:
    - bundle install
    - SERIALIZER=marshal bundle exec ruby test/*_test.rb
    - SERIALIZER=json bundle exec ruby test/*_test.rb
    - SERIALIZER=yaml bundle exec ruby test/*_test.rb

test-ruby32:
  stage: test
  image: ruby:3.2.0
  script:
    - bundle install
    - SERIALIZER=marshal bundle exec ruby test/*_test.rb
    - SERIALIZER=json bundle exec ruby test/*_test.rb
    - SERIALIZER=yaml bundle exec ruby test/*_test.rb
