##
# Plugins
require:
  - standard

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

##
# Extra cops
Style/FrozenStringLiteralComment:
  Enabled: true

##
# Disabled cops (lib-specific)
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
