name: xchan.rb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [3.1, 3.2]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
    - run: SERIALIZER=marshal ./bin/run-tests
    - run: SERIALIZER=json ./bin/run-tests
    - run: SERIALIZER=yaml ./bin/run-tests
    - run: SERIALIZER=plain ./bin/run-tests
