name: xchan.rb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [3.2, 3.3, 3.4]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
    - run: SERIALIZER=marshal; for t in *_test.rb; do ruby test/${t}; done
    - run: SERIALIZER=json; for t in *_test.rb; do ruby test/${t}; done
    - run: SERIALIZER=yaml; for t in *_test.rb; do ruby test/${t}; done
    - run: SERIALIZER=pure; for t in *_test.rb; do ruby test/${t}; done
